In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [30]:
ds = pd.read_csv(r'C:\Users\SUNIL\Desktop\Machine Learning\Machine Learning A-Z (Codes and Datasets)\Part 9 - Dimensionality Reduction\Section 43 - Principal Component Analysis (PCA)\Python\Wine.csv')

In [31]:
ds.shape

(178, 14)

In [32]:
ds.head()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Customer_Segment
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1

In [33]:
ds.isnull().sum()

Alcohol                 0
Malic_Acid              0
Ash                     0
Ash_Alcanity            0
Magnesium               0
Total_Phenols           0
Flavanoids              0
Nonflavanoid_Phenols    0
Proanthocyanins         0
Color_Intensity         0
Hue                     0
OD280                   0
Proline                 0
Customer_Segment        0
dtype: int64

In [34]:
ds.describe()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Customer_Segment
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,1.938202
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,0.775035
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,1.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,1.000000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,2.000000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,3.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,3.000000

In [35]:
x = ds.iloc[:, :-1].values
y = ds.iloc[:, -1].values

In [36]:
x

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [37]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3], dtype=int64)

In [38]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 1)

In [39]:
x_train

array([[1.208e+01, 1.830e+00, 2.320e+00, ..., 1.080e+00, 2.270e+00,
        4.800e+02],
       [1.247e+01, 1.520e+00, 2.200e+00, ..., 1.160e+00, 2.630e+00,
        9.370e+02],
       [1.387e+01, 1.900e+00, 2.800e+00, ..., 1.250e+00, 3.400e+00,
        9.150e+02],
       ...,
       [1.349e+01, 1.660e+00, 2.240e+00, ..., 9.800e-01, 2.780e+00,
        4.720e+02],
       [1.293e+01, 2.810e+00, 2.700e+00, ..., 7.700e-01, 2.310e+00,
        6.000e+02],
       [1.305e+01, 1.650e+00, 2.550e+00, ..., 1.120e+00, 2.510e+00,
        1.105e+03]])

In [40]:
x_test

array([[1.369e+01, 3.260e+00, 2.540e+00, 2.000e+01, 1.070e+02, 1.830e+00,
        5.600e-01, 5.000e-01, 8.000e-01, 5.880e+00, 9.600e-01, 1.820e+00,
        6.800e+02],
       [1.242e+01, 1.610e+00, 2.190e+00, 2.250e+01, 1.080e+02, 2.000e+00,
        2.090e+00, 3.400e-01, 1.610e+00, 2.060e+00, 1.060e+00, 2.960e+00,
        3.450e+02],
       [1.364e+01, 3.100e+00, 2.560e+00, 1.520e+01, 1.160e+02, 2.700e+00,
        3.030e+00, 1.700e-01, 1.660e+00, 5.100e+00, 9.600e-01, 3.360e+00,
        8.450e+02],
       [1.221e+01, 1.190e+00, 1.750e+00, 1.680e+01, 1.510e+02, 1.850e+00,
        1.280e+00, 1.400e-01, 2.500e+00, 2.850e+00, 1.280e+00, 3.070e+00,
        7.180e+02],
       [1.377e+01, 1.900e+00, 2.680e+00, 1.710e+01, 1.150e+02, 3.000e+00,
        2.790e+00, 3.900e-01, 1.680e+00, 6.300e+00, 1.130e+00, 2.930e+00,
        1.375e+03],
       [1.349e+01, 3.590e+00, 2.190e+00, 1.950e+01, 8.800e+01, 1.620e+00,
        4.800e-01, 5.800e-01, 8.800e-01, 5.700e+00, 8.100e-01, 1.820e+00,
        5.800e+02],
       [1.176e+01, 2.680e+00, 2.920e+00, 2.000e+01, 1.030e+02, 1.750e+00,
        2.030e+00, 6.000e-01, 1.050e+00, 3.800e+00, 1.230e+00, 2.500e+00,
        6.070e+02],
       [1.438e+01, 1.870e+00, 2.380e+00, 1.200e+01, 1.020e+02, 3.300e+00,
        3.640e+00, 2.900e-01, 2.960e+00, 7.500e+00, 1.200e+00, 3.000e+00,
        1.547e+03],
       [1.236e+01, 3.830e+00, 2.380e+00, 2.100e+01, 8.800e+01, 2.300e+00,
        9.200e-01, 5.000e-01, 1.040e+00, 7.650e+00, 5.600e-01, 1.580e+00,
        5.200e+02],
       [1.272e+01, 1.750e+00, 2.280e+00, 2.250e+01, 8.400e+01, 1.380e+00,
        1.760e+00, 4.800e-01, 1.630e+00, 3.300e+00, 8.800e-01, 2.420e+00,
        4.880e+02],
       [1.412e+01, 1.480e+00, 2.320e+00, 1.680e+01, 9.500e+01, 2.200e+00,
        2.430e+00, 2.600e-01, 1.570e+00, 5.000e+00, 1.170e+00, 2.820e+00,
        1.280e+03],
       [1.324e+01, 2.590e+00, 2.870e+00, 2.100e+01, 1.180e+02, 2.800e+00,
        2.690e+00, 3.900e-01, 1.820e+00, 4.320e+00, 1.040e+00, 2.930e+00,
        7.350e+02],
       [1.222e+01, 1.290e+00, 1.940e+00, 1.900e+01, 9.200e+01, 2.360e+00,
        2.040e+00, 3.900e-01, 2.080e+00, 2.700e+00, 8.600e-01, 3.020e+00,
        3.120e+02],
       [1.388e+01, 1.890e+00, 2.590e+00, 1.500e+01, 1.010e+02, 3.250e+00,
        3.560e+00, 1.700e-01, 1.700e+00, 5.430e+00, 8.800e-01, 3.560e+00,
        1.095e+03],
       [1.184e+01, 8.900e-01, 2.580e+00, 1.800e+01, 9.400e+01, 2.200e+00,
        2.210e+00, 2.200e-01, 2.350e+00, 3.050e+00, 7.900e-01, 3.080e+00,
        5.200e+02],
       [1.141e+01, 7.400e-01, 2.500e+00, 2.100e+01, 8.800e+01, 2.480e+00,
        2.010e+00, 4.200e-01, 1.440e+00, 3.080e+00, 1.100e+00, 2.310e+00,
        4.340e+02],
       [1.311e+01, 1.900e+00, 2.750e+00, 2.550e+01, 1.160e+02, 2.200e+00,
        1.280e+00, 2.600e-01, 1.560e+00, 7.100e+00, 6.100e-01, 1.330e+00,
        4.250e+02],
       [1.348e+01, 1.810e+00, 2.410e+00, 2.050e+01, 1.000e+02, 2.700e+00,
        2.980e+00, 2.600e-01, 1.860e+00, 5.100e+00, 1.040e+00, 3.470e+00,
        9.200e+02],
       [1.242e+01, 2.550e+00, 2.270e+00, 2.200e+01, 9.000e+01, 1.680e+00,
        1.840e+00, 6.600e-01, 1.420e+00, 2.700e+00, 8.600e-01, 3.300e+00,
        3.150e+02],
       [1.358e+01, 1.660e+00, 2.360e+00, 1.910e+01, 1.060e+02, 2.860e+00,
        3.190e+00, 2.200e-01, 1.950e+00, 6.900e+00, 1.090e+00, 2.880e+00,
        1.515e+03],
       [1.383e+01, 1.650e+00, 2.600e+00, 1.720e+01, 9.400e+01, 2.450e+00,
        2.990e+00, 2.200e-01, 2.290e+00, 5.600e+00, 1.240e+00, 3.370e+00,
        1.265e+03],
       [1.243e+01, 1.530e+00, 2.290e+00, 2.150e+01, 8.600e+01, 2.740e+00,
        3.150e+00, 3.900e-01, 1.770e+00, 3.940e+00, 6.900e-01, 2.840e+00,
        3.520e+02],
       [1.286e+01, 1.350e+00, 2.320e+00, 1.800e+01, 1.220e+02, 1.510e+00,
        1.250e+00, 2.100e-01, 9.400e-01, 4.100e+00, 7.600e-01, 1.290e+00,
        6.300e+02],
       [1.299e+01, 1.670e+00, 2.600e+00, 3.000e+01, 1.390e+02, 3.300e+00,
        2.890e+00, 2.100e-01, 1.960e+00, 3.350e+00, 1.310e+00, 3.500e+00,
        9.850e+02],
       [1.356e+01, 1.710e+00, 2.310e+00, 1.620e+01, 1.170e+02, 3.150e+00,
        3.290e+00, 3.400e-01, 2.340e+00, 6.130e+00, 9.500e-01, 3.380e+00,
        7.950e+02],
       [1.285e+01, 3.270e+00, 2.580e+00, 2.200e+01, 1.060e+02, 1.650e+00,
        6.000e-01, 6.000e-01, 9.600e-01, 5.580e+00, 8.700e-01, 2.110e+00,
        5.700e+02],
       [1.390e+01, 1.680e+00, 2.120e+00, 1.600e+01, 1.010e+02, 3.100e+00,
        3.390e+00, 2.100e-01, 2.140e+00, 6.100e+00, 9.100e-01, 3.330e+00,
        9.850e+02],
       [1.402e+01, 1.680e+00, 2.210e+00, 1.600e+01, 9.600e+01, 2.650e+00,
        2.330e+00, 2.600e-01, 1.980e+00, 4.700e+00, 1.040e+00, 3.590e+00,
        1.035e+03],
       [1.430e+01, 1.920e+00, 2.720e+00, 2.000e+01, 1.200e+02, 2.800e+00,
        3.140e+00, 3.300e-01, 1.970e+00, 6.200e+00, 1.070e+00, 2.650e+00,
        1.280e+03],
       [1.287e+01, 4.610e+00, 2.480e+00, 2.150e+01, 8.600e+01, 1.700e+00,
        6.500e-01, 4.700e-01, 8.600e-01, 7.650e+00, 5.400e-01, 1.860e+00,
        6.250e+02],
       [1.229e+01, 1.410e+00, 1.980e+00, 1.600e+01, 8.500e+01, 2.550e+00,
        2.500e+00, 2.900e-01, 1.770e+00, 2.900e+00, 1.230e+00, 2.740e+00,
        4.280e+02],
       [1.348e+01, 1.670e+00, 2.640e+00, 2.250e+01, 8.900e+01, 2.600e+00,
        1.100e+00, 5.200e-01, 2.290e+00, 1.175e+01, 5.700e-01, 1.780e+00,
        6.200e+02],
       [1.279e+01, 2.670e+00, 2.480e+00, 2.200e+01, 1.120e+02, 1.480e+00,
        1.360e+00, 2.400e-01, 1.260e+00, 1.080e+01, 4.800e-01, 1.470e+00,
        4.800e+02],
       [1.420e+01, 1.760e+00, 2.450e+00, 1.520e+01, 1.120e+02, 3.270e+00,
        3.390e+00, 3.400e-01, 1.970e+00, 6.750e+00, 1.050e+00, 2.850e+00,
        1.450e+03],
       [1.145e+01, 2.400e+00, 2.420e+00, 2.000e+01, 9.600e+01, 2.900e+00,
        2.790e+00, 3.200e-01, 1.830e+00, 3.250e+00, 8.000e-01, 3.390e+00,
        6.250e+02],
       [1.162e+01, 1.990e+00, 2.280e+00, 1.800e+01, 9.800e+01, 3.020e+00,
        2.260e+00, 1.700e-01, 1.350e+00, 3.250e+00, 1.160e+00, 2.960e+00,
        3.450e+02],
       [1.200e+01, 1.510e+00, 2.420e+00, 2.200e+01, 8.600e+01, 1.450e+00,
        1.250e+00, 5.000e-01, 1.630e+00, 3.600e+00, 1.050e+00, 2.650e+00,
        4.500e+02],
       [1.272e+01, 1.810e+00, 2.200e+00, 1.880e+01, 8.600e+01, 2.200e+00,
        2.530e+00, 2.600e-01, 1.770e+00, 3.900e+00, 1.160e+00, 3.140e+00,
        7.140e+02],
       [1.208e+01, 1.390e+00, 2.500e+00, 2.250e+01, 8.400e+01, 2.560e+00,
        2.290e+00, 4.300e-01, 1.040e+00, 2.900e+00, 9.300e-01, 3.190e+00,
        3.850e+02],
       [1.410e+01, 2.020e+00, 2.400e+00, 1.880e+01, 1.030e+02, 2.750e+00,
        2.920e+00, 3.200e-01, 2.380e+00, 6.200e+00, 1.070e+00, 2.750e+00,
        1.060e+03],
       [1.374e+01, 1.670e+00, 2.250e+00, 1.640e+01, 1.180e+02, 2.600e+00,
        2.900e+00, 2.100e-01, 1.620e+00, 5.850e+00, 9.200e-01, 3.200e+00,
        1.060e+03],
       [1.237e+01, 9.400e-01, 1.360e+00, 1.060e+01, 8.800e+01, 1.980e+00,
        5.700e-01, 2.800e-01, 4.200e-01, 1.950e+00, 1.050e+00, 1.820e+00,
        5.200e+02],
       [1.373e+01, 4.360e+00, 2.260e+00, 2.250e+01, 8.800e+01, 1.280e+00,
        4.700e-01, 5.200e-01, 1.150e+00, 6.620e+00, 7.800e-01, 1.750e+00,
        5.200e+02],
       [1.422e+01, 3.990e+00, 2.510e+00, 1.320e+01, 1.280e+02, 3.000e+00,
        3.040e+00, 2.000e-01, 2.080e+00, 5.100e+00, 8.900e-01, 3.530e+00,
        7.600e+02],
       [1.422e+01, 1.700e+00, 2.300e+00, 1.630e+01, 1.180e+02, 3.200e+00,
        3.000e+00, 2.600e-01, 2.030e+00, 6.380e+00, 9.400e-01, 3.310e+00,
        9.700e+02],
       [1.305e+01, 1.770e+00, 2.100e+00, 1.700e+01, 1.070e+02, 3.000e+00,
        3.000e+00, 2.800e-01, 2.030e+00, 5.040e+00, 8.800e-01, 3.350e+00,
        8.850e+02],
       [1.233e+01, 9.900e-01, 1.950e+00, 1.480e+01, 1.360e+02, 1.900e+00,
        1.850e+00, 3.500e-01, 2.760e+00, 3.400e+00, 1.060e+00, 2.310e+00,
        7.500e+02],
       [1.376e+01, 1.530e+00, 2.700e+00, 1.950e+01, 1.320e+02, 2.950e+00,
        2.740e+00, 5.000e-01, 1.350e+00, 5.400e+00, 1.250e+00, 3.000e+00,
        1.235e+03],
       [1.419e+01, 1.590e+00, 2.480e+00, 1.650e+01, 1.080e+02, 3.300e+00,
        3.930e+00, 3.200e-01, 1.860e+00, 8.700e+00, 1.230e+00, 2.820e+00,
        1.680e+03],
       [1.372e+01, 1.430e+00, 2.500e+00, 1.670e+01, 1.080e+02, 3.400e+00,
        3.670e+00, 1.900e-01, 2.040e+00, 6.800e+00, 8.900e-01, 2.870e+00,
        1.285e+03],
       [1.179e+01, 2.130e+00, 2.780e+00, 2.850e+01, 9.200e+01, 2.130e+00,
        2.240e+00, 5.800e-01, 1.760e+00, 3.000e+00, 9.700e-01, 2.440e+00,
        4.660e+02],
       [1.416e+01, 2.510e+00, 2.480e+00, 2.000e+01, 9.100e+01, 1.680e+00,
        7.000e-01, 4.400e-01, 1.240e+00, 9.700e+00, 6.200e-01, 1.710e+00,
        6.600e+02],
       [1.332e+01, 3.240e+00, 2.380e+00, 2.150e+01, 9.200e+01, 1.930e+00,
        7.600e-01, 4.500e-01, 1.250e+00, 8.420e+00, 5.500e-01, 1.620e+00,
        6.500e+02],
       [1.375e+01, 1.730e+00, 2.410e+00, 1.600e+01, 8.900e+01, 2.600e+00,
        2.760e+00, 2.900e-01, 1.810e+00, 5.600e+00, 1.150e+00, 2.900e+00,
        1.320e+03]])

In [41]:
y_train

array([2, 2, 1, 2, 3, 2, 2, 1, 3, 2, 3, 1, 2, 1, 2, 1, 3, 3, 3, 3, 2, 2,
       1, 3, 1, 2, 3, 1, 2, 1, 3, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 3, 2, 2,
       2, 2, 1, 1, 1, 3, 1, 2, 3, 3, 1, 2, 1, 2, 2, 1, 3, 2, 2, 3, 3, 2,
       2, 2, 3, 3, 2, 1, 2, 1, 3, 2, 2, 1, 1, 2, 1, 1, 1, 3, 1, 3, 3, 1,
       2, 2, 3, 1, 2, 2, 1, 1, 1, 2, 2, 1, 3, 3, 2, 2, 2, 1, 3, 3, 3, 3,
       3, 2, 1, 1, 3, 2, 2, 3, 2, 3, 3, 2, 3, 1], dtype=int64)

In [42]:
y_test

array([3, 2, 1, 2, 1, 3, 2, 1, 3, 2, 1, 1, 2, 1, 2, 2, 3, 1, 2, 1, 1, 2,
       3, 2, 1, 3, 1, 1, 1, 3, 2, 3, 3, 1, 2, 2, 2, 2, 2, 1, 1, 2, 3, 1,
       1, 1, 2, 1, 1, 1, 2, 3, 3, 1], dtype=int64)

In [43]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [44]:
x_train

array([[-1.10453814, -0.53090202, -0.13625741, ...,  0.51645351,
        -0.4182397 , -0.8519466 ],
       [-0.60884898, -0.79223988, -0.57322083, ...,  0.85655034,
         0.07607378,  0.73976188],
       [ 1.17054803, -0.47189024,  1.61159627, ...,  1.23915929,
         1.13335541,  0.66313697],
       ...,
       [ 0.68756884, -0.67421633, -0.42756636, ...,  0.09133246,
         0.28203774, -0.87981021],
       [-0.02418996,  0.29526283,  1.24746009, ..., -0.80142174,
        -0.36331598, -0.43399251],
       [ 0.12832978, -0.68264658,  0.70125581, ...,  0.68650193,
        -0.08869738,  1.3248976 ]])

In [45]:
x_test

array([[ 0.94176842,  0.67462425,  0.66484219,  0.09638535,  0.66003794,
        -0.6493993 , -1.39119415,  1.09918838, -1.26802979,  0.38990328,
         0.00630825, -1.03613156, -0.15535646],
       [-0.67239887, -0.7163676 , -0.60963445,  0.88062311,  0.73519378,
        -0.3776237 ,  0.14995588, -0.23626156,  0.1085473 , -1.21734921,
         0.4314293 ,  0.52919448, -1.32214495],
       [ 0.87821852,  0.53974019,  0.73766943, -1.40935114,  1.33644046,
         0.74145233,  1.09680622, -1.65517712,  0.19352119,  0.06172083,
         0.00630825,  1.07843169,  0.41933041],
       [-0.93930842, -1.07043825, -2.21183366, -0.90743898,  3.96689471,
        -0.6174257 , -0.66594708, -1.90557398,  1.62108262, -0.8849593 ,
         1.3666956 ,  0.68023471, -0.02300433],
       [ 1.04344824, -0.47189024,  1.17463285, -0.81333045,  1.26128463,
         1.22105634,  0.8550572 ,  0.18106655,  0.22751075,  0.5666169 ,
         0.72901403,  0.48800169,  2.2652943 ],
       [ 0.68756884,  0.95282261, -0.60963445, -0.0604622 , -0.76792293,
        -0.98512211, -1.47177715,  1.76691335, -1.13207156,  0.31416887,
        -0.63137332, -1.03613156, -0.50365153],
       [-1.51125746,  0.18566954,  2.04855969,  0.09638535,  0.3594146 ,
        -0.77729371,  0.08951862,  1.93384459, -0.84316032, -0.48524991,
         1.15413508, -0.10242831, -0.40961186],
       [ 1.81875694, -0.497181  ,  0.0822243 , -2.41317547,  0.28425877,
         1.70066035,  1.71125166, -0.65358966,  2.40284244,  1.07151297,
         1.02659876,  0.5841182 ,  2.86436183],
       [-0.74865874,  1.1551487 ,  0.0822243 ,  0.41008045, -0.76792293,
         0.10198032, -1.02857061,  1.09918838, -0.8601551 ,  1.13462498,
        -1.69417595, -1.36567389, -0.71262857],
       [-0.29109951, -0.59834405, -0.28191188,  0.88062311, -1.06854627,
        -1.36880532, -0.18244903,  0.93225714,  0.14253686, -0.69562327,
        -0.33378859, -0.21227575, -0.824083  ],
       [ 1.4882975 , -0.82596089, -0.13625741, -0.90743898, -0.24183208,
        -0.05788769,  0.49243366, -0.90398653,  0.04056818,  0.01964616,
         0.89906245,  0.33696146,  1.93441398],
       [ 0.36981938,  0.10979725,  1.8664916 ,  0.41008045,  1.48675213,
         0.90132033,  0.75432844,  0.18106655,  0.46543765, -0.26646161,
         0.34640509,  0.48800169,  0.03620583],
       [-0.92659844, -0.98613571, -1.51997491, -0.21730975, -0.46729959,
         0.19790112,  0.0995915 ,  0.18106655,  0.9073019 , -0.9480713 ,
        -0.4188128 ,  0.61158006, -1.43708232],
       [ 1.18325801, -0.4803205 ,  0.84691029, -1.47209017,  0.20910293,
         1.62072635,  1.63066865, -1.65517712,  0.26150031,  0.20056725,
        -0.33378859,  1.35305029,  1.2900681 ],
       [-1.40957763, -1.32334586,  0.81049667, -0.53100486, -0.31698792,
        -0.05788769,  0.27083039, -1.23784901,  1.36616093, -0.80080995,
        -0.71639753,  0.69396564, -0.71262857],
       [-1.95610671, -1.44979966,  0.51918772,  0.41008045, -0.76792293,
         0.38974272,  0.06937287,  0.43146341, -0.18036394, -0.78818755,
         0.60147772, -0.36331598, -1.01216233],
       [ 0.20458966, -0.47189024,  1.42952818,  1.82170842,  1.33644046,
        -0.05788769, -0.66594708, -0.90398653,  0.0235734 ,  0.90321428,
        -1.48161542, -1.70894714, -1.04350889],
       [ 0.67485886, -0.54776253,  0.19146515,  0.2532329 ,  0.13394709,
         0.74145233,  1.04644184, -0.90398653,  0.53341677,  0.06172083,
         0.34640509,  1.22947192,  0.68055172],
       [-0.67239887,  0.07607624, -0.3183255 ,  0.72377556, -0.61761126,
        -0.88920131, -0.10186602,  2.43463832, -0.2143535 , -0.9480713 ,
        -0.4188128 ,  0.99604611, -1.42663347],
       [ 0.80195865, -0.67421633,  0.00939706, -0.18594024,  0.58488211,
         0.99724114,  1.25797224, -1.23784901,  0.68636978,  0.81906494,
         0.55896561,  0.41934704,  2.7529074 ],
       [ 1.11970812, -0.68264658,  0.8833239 , -0.78196094, -0.31698792,
         0.34178232,  1.05651472, -1.23784901,  1.26419226,  0.2720942 ,
         1.19664718,  1.09216262,  1.88216972],
       [-0.65968889, -0.78380963, -0.24549827,  0.566928  , -0.9182346 ,
         0.80539953,  1.21768073,  0.18106655,  0.38046376, -0.42634537,
        -1.14151858,  0.36442332, -1.29776429],
       [-0.11315981, -0.93555419, -0.13625741, -0.53100486,  1.78737548,
        -1.16097692, -0.6961657 , -1.32131463, -1.03010289, -0.35902589,
        -0.84393385, -1.76387087, -0.32950399],
       [ 0.05206991, -0.66578608,  0.8833239 ,  3.23333638,  3.06502468,
         1.70066035,  0.95578596, -1.32131463,  0.70336456, -0.67458593,
         1.49423192,  1.27066471,  0.90694352],
       [ 0.77653869, -0.63206506, -0.17267103, -1.09565604,  1.4115963 ,
         1.46085835,  1.358701  , -0.23626156,  1.34916615,  0.49508996,
        -0.03620386,  1.10589355,  0.24518288],
       [-0.12586979,  0.6830545 ,  0.81049667,  0.72377556,  0.58488211,
        -0.93716171, -1.35090264,  1.93384459, -0.99611333,  0.26367926,
        -0.3763007 , -0.63793459, -0.53848104],
       [ 1.20867797, -0.65735582, -0.86452978, -1.15839506,  0.20910293,
         1.38092435,  1.45942976, -1.32131463,  1.00927058,  0.48246756,
        -0.20625228,  1.0372389 ,  0.90694352],
       [ 1.36119771, -0.65735582, -0.53680721, -1.15839506, -0.16667625,
         0.66151833,  0.3917049 , -0.90398653,  0.73735412, -0.10657786,
         0.34640509,  1.39424308,  1.08109105],
       [ 1.71707711, -0.45502974,  1.32028733,  0.09638535,  1.6370638 ,
         0.90132033,  1.20760786, -0.31972718,  0.72035934,  0.52454223,
         0.4739414 ,  0.10353564,  1.93441398],
       [-0.10044983,  1.81270848,  0.44636048,  0.566928  , -0.9182346 ,
        -0.85722771, -1.30053826,  0.84879152, -1.16606112,  1.13462498,
        -1.77920016, -0.98120784, -0.34691875],
       [-0.83762859, -0.88497267, -1.37432044, -1.15839506, -0.99339044,
         0.50165032,  0.56294379, -0.65358966,  0.38046376, -0.86392196,
         1.15413508,  0.22711401, -1.03306004],
       [ 0.67485886, -0.66578608,  1.02897838,  0.88062311, -0.6927671 ,
         0.58158433, -0.84725884,  1.26611962,  1.26419226,  2.85968655,
        -1.65166384, -1.09105528, -0.3643335 ],
       [-0.20212966,  0.17723928,  0.44636048,  0.72377556,  1.03581712,
        -1.20893732, -0.58536407, -1.07091777, -0.48626996,  2.45997716,
        -2.03427278, -1.51671412, -0.8519466 ],
       [ 1.58997732, -0.58991379,  0.33711963, -1.40935114,  1.03581712,
         1.65269995,  1.45942976, -0.23626156,  0.72035934,  0.75595293,
         0.38891719,  0.37815425,  2.5265156 ],
       [-1.90526679, -0.05037756,  0.22787877,  0.09638535, -0.16667625,
         1.06118834,  0.8550572 , -0.4031928 ,  0.48243243, -0.71666061,
        -0.67388543,  1.11962448, -0.34691875],
       [-1.68919716, -0.39601796, -0.28191188, -0.53100486, -0.01636458,
         1.25302994,  0.32119477, -1.65517712, -0.33331695, -0.71666061,
         0.85655034,  0.52919448, -1.32214495],
       [-1.20621797, -0.80067013,  0.22787877,  0.72377556, -0.9182346 ,
        -1.25689772, -0.6961657 ,  1.09918838,  0.14253686, -0.56939925,
         0.38891719,  0.10353564, -0.95643512],
       [-0.29109951, -0.54776253, -0.57322083, -0.28004877, -0.9182346 ,
        -0.05788769,  0.59316242, -0.90398653,  0.38046376, -0.44317524,
         0.85655034,  0.77635122, -0.03693613],
       [-1.10453814, -0.90183318,  0.51918772,  0.88062311, -1.06854627,
         0.51763713,  0.3514134 ,  0.51492903, -0.8601551 , -0.86392196,
        -0.12122807,  0.84500587, -1.18282692],
       [ 1.46287754, -0.3707272 ,  0.15505154, -0.28004877,  0.3594146 ,
         0.82138633,  0.98600459, -0.4031928 ,  1.41714527,  0.52454223,
         0.4739414 ,  0.24084495,  1.16816482],
       [ 1.00531831, -0.66578608, -0.39115274, -1.03291702,  1.48675213,
         0.58158433,  0.96585883, -1.32131463,  0.12554208,  0.37728088,
        -0.16374017,  0.8587368 ,  1.16816482],
       [-0.73594876, -1.28119459, -3.63196478, -2.85234862, -0.76792293,
        -0.4095973 , -1.38112127, -0.73705528, -1.91383139, -1.26363135,
         0.38891719, -1.03613156, -0.71262857],
       [ 0.99260833,  1.60195214, -0.35473912,  0.88062311, -0.76792293,
        -1.52867332, -1.48185003,  1.26611962, -0.67321253,  0.70125585,
        -0.75890964, -1.13224808, -0.71262857],
       [ 1.61539728,  1.29003276,  0.55560134, -2.03674135,  2.23831049,
         1.22105634,  1.1068791 , -1.40478025,  0.9073019 ,  0.06172083,
        -0.29127649,  1.3118575 ,  0.1232796 ],
       [ 1.61539728, -0.64049532, -0.20908465, -1.06428653,  1.48675213,
         1.54079235,  1.06658759, -0.90398653,  0.82232801,  0.60027664,
        -0.07871596,  1.00977704,  0.85469926],
       [ 0.12832978, -0.58148354, -0.93735702, -0.84469996,  0.66003794,
         1.22105634,  1.06658759, -0.73705528,  0.82232801,  0.03647603,
        -0.33378859,  1.06470076,  0.55864844],
       [-0.78678868, -1.23904332, -1.48356129, -1.53482919,  2.83955717,
        -0.5374917 , -0.09179314, -0.15279594,  2.06294687, -0.6535486 ,
         0.4314293 , -0.36331598,  0.0884501 ],
       [ 1.03073827, -0.78380963,  1.24746009, -0.0604622 ,  2.53893383,
         1.14112234,  0.80469282,  1.09918838, -0.33331695,  0.18794485,
         1.23915929,  0.5841182 ,  1.7776812 ],
       [ 1.57726735, -0.7332281 ,  0.44636048, -1.00154751,  0.73519378,
         1.70066035,  2.00336506, -0.4031928 ,  0.53341677,  1.57640904,
         1.15413508,  0.33696146,  3.32759427],
       [ 0.97989835, -0.86811216,  0.51918772, -0.93880849,  0.73519378,
         1.86052836,  1.74147029, -1.48824587,  0.83932279,  0.77699026,
        -0.29127649,  0.40561611,  1.95182873],
       [-1.47312752, -0.27799441,  1.53876904,  2.76279373, -0.46729959,
        -0.16979529,  0.30104902,  1.76691335,  0.36346898, -0.82184729,
         0.04882035, -0.18481389, -0.90070791],
       [ 1.53913741,  0.04235523,  0.44636048,  0.09638535, -0.54245543,
        -0.88920131, -1.25017388,  0.59839465, -0.52025952,  1.99715576,
        -1.43910332, -1.1871718 , -0.22501547],
       [ 0.47149921,  0.65776374,  0.0822243 ,  0.566928  , -0.46729959,
        -0.4895313 , -1.18973663,  0.68186028, -0.50326474,  1.45859996,
        -1.73668805, -1.31075017, -0.25984498],
       [ 1.01802829, -0.61520455,  0.19146515, -1.15839506, -0.6927671 ,
         0.58158433,  0.82483857, -0.65358966,  0.44844287,  0.2720942 ,
         0.81403824,  0.4468089 ,  2.07373201]])

# Applying PCA

In [46]:
from sklearn.decomposition import PCA
model = PCA(n_components = 2)
x_train = model.fit_transform(x_train)
x_test = model.transform(x_test)

In [47]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)
model.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [48]:
y_pred = model.predict(x_test)
y_pred

array([3, 2, 1, 2, 1, 3, 2, 1, 3, 2, 1, 1, 2, 1, 2, 2, 3, 1, 2, 1, 1, 2,
       3, 1, 1, 3, 1, 1, 1, 3, 2, 3, 3, 1, 2, 2, 2, 2, 2, 1, 1, 2, 3, 1,
       1, 1, 2, 1, 1, 1, 2, 3, 3, 1], dtype=int64)

In [50]:
y_test

array([3, 2, 1, 2, 1, 3, 2, 1, 3, 2, 1, 1, 2, 1, 2, 2, 3, 1, 2, 1, 1, 2,
       3, 2, 1, 3, 1, 1, 1, 3, 2, 3, 3, 1, 2, 2, 2, 2, 2, 1, 1, 2, 3, 1,
       1, 1, 2, 1, 1, 1, 2, 3, 3, 1], dtype=int64)

In [51]:
y_pred_ds = pd.DataFrame(y_pred, columns = ['Predicted Values'])
y_pred_ds

    Predicted Values
0                  3
1                  2
2                  1
3                  2
4                  1
5                  3
6                  2
7                  1
8                  3
9                  2
10                 1
11                 1
12                 2
13                 1
14                 2
15                 2
16                 3
17                 1
18                 2
19                 1
20                 1
21                 2
22                 3
23                 1
24                 1
25                 3
26                 1
27                 1
28                 1
29                 3
30                 2
31                 3
32                 3
33                 1
34                 2
35                 2
36                 2
37                 2
38                 2
39                 1
40                 1
41                 2
42                 3
43                 1
44                 1
45                 1
46                 2
47                 1
48                 1
49                 1
50                 2
51                 3
52                 3
53                 1

In [52]:
y_test_ds = pd.DataFrame(y_test, columns = ['Actual Values'])
y_test_ds

    Actual Values
0               3
1               2
2               1
3               2
4               1
5               3
6               2
7               1
8               3
9               2
10              1
11              1
12              2
13              1
14              2
15              2
16              3
17              1
18              2
19              1
20              1
21              2
22              3
23              2
24              1
25              3
26              1
27              1
28              1
29              3
30              2
31              3
32              3
33              1
34              2
35              2
36              2
37              2
38              2
39              1
40              1
41              2
42              3
43              1
44              1
45              1
46              2
47              1
48              1
49              1
50              2
51              3
52              3
53              1

In [53]:
pd.concat([y_test_ds, y_pred_ds], axis = 1)

    Actual Values  Predicted Values
0               3                 3
1               2                 2
2               1                 1
3               2                 2
4               1                 1
5               3                 3
6               2                 2
7               1                 1
8               3                 3
9               2                 2
10              1                 1
11              1                 1
12              2                 2
13              1                 1
14              2                 2
15              2                 2
16              3                 3
17              1                 1
18              2                 2
19              1                 1
20              1                 1
21              2                 2
22              3                 3
23              2                 1
24              1                 1
25              3                 3
26              1                 1
27              1                 1
28              1                 1
29              3                 3
30              2                 2
31              3                 3
32              3                 3
33              1                 1
34              2                 2
35              2                 2
36              2                 2
37              2                 2
38              2                 2
39              1                 1
40              1                 1
41              2                 2
42              3                 3
43              1                 1
44              1                 1
45              1                 1
46              2                 2
47              1                 1
48              1                 1
49              1                 1
50              2                 2
51              3                 3
52              3                 3
53              1                 1

In [54]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[23,  0,  0],
       [ 1, 18,  0],
       [ 0,  0, 12]], dtype=int64)

In [55]:
accuracy_score(y_test, y_pred)

0.9814814814814815